<?php
echo "<!--

=========================================================
* Now UI Kit - v1.3.0
=========================================================

* Product Page: https://www.creative-tim.com/product/now-ui-kit
* Copyright 2019 Creative Tim (http://www.creative-tim.com)
* Licensed under MIT (https://github.com/creativetimofficial/now-ui-kit/blob/master/LICENSE.md)

* Designed by www.invisionapp.com Coded by www.creative-tim.com

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

-->";
echo "<!DOCTYPE html>";
echo "<html lang=\"en\">";

echo "<head>";
  echo "<meta charset=\"utf-8\" />";
  echo "<link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"./assets/img/apple-icon.png\">";
  echo "<link rel=\"icon\" type=\"image/png\" href=\"./assets/img/favicon.png\">";
  echo "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\" />";
  echo "<title>";
    echo "Now UI Kit by Creative Tim";
  echo "</title>";
  echo "<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />";
  echo "<!--     Fonts and icons     -->";
  echo "<link href=\"https://fonts.googleapis.com/css?family=Montserrat:400,700,200\" rel=\"stylesheet\" />";
  echo "<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.1/css/all.css\" integrity=\"sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr\" crossorigin=\"anonymous\">";
  echo "<!-- CSS Files -->";
  echo "<link href=\"./assets/css/bootstrap.min.css\" rel=\"stylesheet\" />";
  echo "<link href=\"./assets/css/now-ui-kit.css?v=1.3.0\" rel=\"stylesheet\" />";
  echo "<!-- CSS Just for demo purpose, don't include it in your project -->";
  echo "<link href=\"./assets/demo/demo.css\" rel=\"stylesheet\" />";
echo "</head>";

echo "<body class=\"index-page sidebar-collapse\">";
  echo "<!-- Navbar -->";
  echo "<nav class=\"navbar navbar-expand-lg bg-primary fixed-top navbar-transparent \" color-on-scroll=\"400\">";
    echo "<div class=\"container\">";
      echo "<div class=\"navbar-translate\">";
        echo "<a class=\"navbar-brand\" href=\"https://demos.creative-tim.com/now-ui-kit/index.html\" rel=\"tooltip\" title=\"Designed by Invision. Coded by Creative Tim\" data-placement=\"bottom\" target=\"_blank\">";
          echo "Now Ui Kit";
        echo "</a>";
        echo "<button class=\"navbar-toggler navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navigation\" aria-controls=\"navigation-index\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
          echo "<span class=\"navbar-toggler-bar top-bar\"></span>";
          echo "<span class=\"navbar-toggler-bar middle-bar\"></span>";
          echo "<span class=\"navbar-toggler-bar bottom-bar\"></span>";
        echo "</button>";
      echo "</div>";
      echo "<div class=\"collapse navbar-collapse justify-content-end\" id=\"navigation\" data-nav-image=\"./assets/img/blurred-image-1.jpg\">";
        echo "<ul class=\"navbar-nav\">";
          echo "<li class=\"nav-item\">";
            echo "<a class=\"nav-link\" href=\"javascript:void(0)\" onclick=\"scrollToDownload()\">";
              echo "<i class=\"now-ui-icons arrows-1_cloud-download-93\"></i>";
              echo "<p>Download</p>";
            echo "</a>";
          echo "</li>";
          echo "<li class=\"nav-item dropdown\">";
            echo "<a href=\"#\" class=\"nav-link dropdown-toggle\" id=\"navbarDropdownMenuLink1\" data-toggle=\"dropdown\">";
              echo "<i class=\"now-ui-icons design_app\"></i>";
              echo "<p>Components</p>";
            echo "</a>";
            echo "<div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"navbarDropdownMenuLink1\">";
              echo "<a class=\"dropdown-item\" href=\"./index.html\">";
                echo "<i class=\"now-ui-icons business_chart-pie-36\"></i> All components";
              echo "</a>";
              echo "<a class=\"dropdown-item\" target=\"_blank\" href=\"https://demos.creative-tim.com/now-ui-kit/docs/1.0/getting-started/introduction.html\">";
                echo "<i class=\"now-ui-icons design_bullet-list-67\"></i> Documentation";
              echo "</a>";
            echo "</div>";
          echo "</li>";
          echo "<li class=\"nav-item\">";
            echo "<a class=\"nav-link btn btn-neutral\" href=\"https://www.creative-tim.com/product/now-ui-kit-pro\" target=\"_blank\">";
              echo "<i class=\"now-ui-icons arrows-1_share-66\"></i>";
              echo "<p>Upgrade to PRO</p>";
            echo "</a>";
          echo "</li>";
          echo "<li class=\"nav-item\">";
            echo "<a class=\"nav-link\" rel=\"tooltip\" title=\"Follow us on Twitter\" data-placement=\"bottom\" href=\"https://twitter.com/CreativeTim\" target=\"_blank\">";
              echo "<i class=\"fab fa-twitter\"></i>";
              echo "<p class=\"d-lg-none d-xl-none\">Twitter</p>";
            echo "</a>";
          echo "</li>";
          echo "<li class=\"nav-item\">";
            echo "<a class=\"nav-link\" rel=\"tooltip\" title=\"Like us on Facebook\" data-placement=\"bottom\" href=\"https://www.facebook.com/CreativeTim\" target=\"_blank\">";
              echo "<i class=\"fab fa-facebook-square\"></i>";
              echo "<p class=\"d-lg-none d-xl-none\">Facebook</p>";
            echo "</a>";
          echo "</li>";
          echo "<li class=\"nav-item\">";
            echo "<a class=\"nav-link\" rel=\"tooltip\" title=\"Follow us on Instagram\" data-placement=\"bottom\" href=\"https://www.instagram.com/CreativeTimOfficial\" target=\"_blank\">";
              echo "<i class=\"fab fa-instagram\"></i>";
              echo "<p class=\"d-lg-none d-xl-none\">Instagram</p>";
            echo "</a>";
          echo "</li>";
        echo "</ul>";
      echo "</div>";
    echo "</div>";
  echo "</nav>";
  echo "<!-- End Navbar -->";
  echo "<div class=\"wrapper\">";
    echo "<div class=\"page-header clear-filter\" filter-color=\"orange\">";
      echo "<div class=\"page-header-image\" data-parallax=\"true\" style=\"background-image:url('./assets/img/header.jpg');\">";
      echo "</div>";
      echo "<div class=\"container\">";
        echo "<div class=\"content-center brand\">";
          echo "<img class=\"n-logo\" src=\"./assets/img/now-logo.png\" alt=\"\">";
          echo "<h1 class=\"h1-seo\">Now UI Kit.</h1>";
          echo "<h3>A beautiful Bootstrap 4 UI kit. Yours free.</h3>";
        echo "</div>";
        echo "<h6 class=\"category category-absolute\">Designed by";
          echo "<a href=\"http://invisionapp.com/\" target=\"_blank\">";
            echo "<img src=\"./assets/img/invision-white-slim.png\" class=\"invision-logo\" />";
          echo "</a>. Coded by";
          echo "<a href=\"https://www.creative-tim.com\" target=\"_blank\">";
            echo "<img src=\"./assets/img/creative-tim-white-slim2.png\" class=\"creative-tim-logo\" />";
          echo "</a>.</h6>";
      echo "</div>";
    echo "</div>";
    echo "<div class=\"main\">";
      echo "<div class=\"section section-images\">";
        echo "<div class=\"container\">";
          echo "<div class=\"row\">";
            echo "<div class=\"col-md-12\">";
              echo "<div class=\"hero-images-container\">";
                echo "<img src=\"assets/img/hero-image-1.png\" alt=\"\">";
              echo "</div>";
              echo "<div class=\"hero-images-container-1\">";
                echo "<img src=\"assets/img/hero-image-2.png\" alt=\"\">";
              echo "</div>";
              echo "<div class=\"hero-images-container-2\">";
                echo "<img src=\"assets/img/hero-image-3.png\" alt=\"\">";
              echo "</div>";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section section-basic\" id=\"basic-elements\">";
        echo "<div class=\"container\">";
          echo "<h3 class=\"title\">Basic Elements</h3>";
          echo "<h4>Buttons</h4>";
          echo "<p class=\"category\">Pick your style</p>";
          echo "<div class=\"row\">";
            echo "<div class=\"col-md-10\">";
              echo "<button class=\"btn btn-primary\" type=\"button\">Default</button>";
              echo "<button class=\"btn btn-primary btn-round\" type=\"button\">Round</button>";
              echo "<button class=\"btn btn-primary btn-round\" type=\"button\">";
                echo "<i class=\"now-ui-icons ui-2_favourite-28\"></i> With Icon";
              echo "</button>";
              echo "<button class=\"btn btn-primary btn-icon btn-round\" type=\"button\">";
                echo "<i class=\"now-ui-icons ui-2_favourite-28\"></i>";
              echo "</button>";
              echo "<button class=\"btn btn-primary btn-outline-primary btn-round\" type=\"button\">Outline</button>";
            echo "</div>";
          echo "</div>";
          echo "<p class=\"category\">Pick your size</p>";
          echo "<div class=\"row\">";
            echo "<div class=\"col-md-10\">";
              echo "<button class=\"btn btn-primary btn-sm\">Small</button>";
              echo "<button class=\"btn btn-primary\">Regular</button>";
              echo "<button class=\"btn btn-primary btn-lg\">Large</button>";
            echo "</div>";
          echo "</div>";
          echo "<p class=\"category\">Pick your color</p>";
          echo "<div class=\"row\">";
            echo "<div class=\"col-md-10\">";
              echo "<button class=\"btn\">Default</button>";
              echo "<button class=\"btn btn-primary\">Primary</button>";
              echo "<button class=\"btn btn-info\">Info</button>";
              echo "<button class=\"btn btn-success\">Success</button>";
              echo "<button class=\"btn btn-warning\">Warning</button>";
              echo "<button class=\"btn btn-danger\">Danger</button>";
              echo "<button class=\"btn btn-neutral\">Neutral</button>";
            echo "</div>";
          echo "</div>";
          echo "<h4>Links</h4>";
          echo "<div class=\"row\">";
            echo "<div class=\"col-md-8\">";
              echo "<button class=\"btn btn-link\">Default</button>";
              echo "<button class=\"btn btn-link btn-primary \">Primary</button>";
              echo "<button class=\"btn btn-link btn-info\">Info</button>";
              echo "<button class=\"btn btn-link btn-success\">Success</button>";
              echo "<button class=\"btn btn-link btn-warning\">Warning</button>";
              echo "<button class=\"btn btn-link btn-danger\">Danger</button>";
            echo "</div>";
          echo "</div>";
          echo "<div class=\"space-70\"></div>";
          echo "<div id=\"inputs\">";
            echo "<h4>Inputs</h4>";
            echo "<p class=\"category\">Form Controls</p>";
            echo "<div class=\"row\">";
              echo "<div class=\"col-sm-6 col-lg-3\">";
                echo "<div class=\"form-group\">";
                  echo "<input type=\"text\" value=\"\" placeholder=\"Regular\" class=\"form-control\" />";
                echo "</div>";
              echo "</div>";
              echo "<div class=\"col-sm-6 col-lg-3\">";
                echo "<div class=\"form-group has-success\">";
                  echo "<input type=\"text\" value=\"Success\" class=\"form-control form-control-success\" />";
                echo "</div>";
              echo "</div>";
              echo "<div class=\"col-sm-6 col-lg-3\">";
                echo "<div class=\"form-group has-danger\">";
                  echo "<input type=\"email\" value=\"Error Input\" class=\"form-control form-control-danger\" />";
                echo "</div>";
              echo "</div>";
              echo "<div class=\"col-sm-6 col-lg-3\">";
                echo "<div class=\"input-group\">";
                  echo "<div class=\"input-group-prepend\">";
                    echo "<span class=\"input-group-text\"><i class=\"fa fa-user-circle\"></i></span>";
                  echo "</div>";
                  echo "<input type=\"text\" class=\"form-control\" placeholder=\"Left Font Awesome Icon\">";
                echo "</div>";
              echo "</div>";
              echo "<div class=\"col-sm-6 col-lg-3\">";
                echo "<div class=\"input-group\">";
                  echo "<input type=\"text\" class=\"form-control\" placeholder=\"Right Nucleo Icon\">";
                  echo "<div class=\"input-group-append\">";
                    echo "<span class=\"input-group-text\"><i class=\"now-ui-icons users_single-02\"></i></span>";
                  echo "</div>";
                echo "</div>";
              echo "</div>";
            echo "</div>";
          echo "</div>";
          echo "<div class=\"space-70\"></div>";
          echo "<div class=\"row\" id=\"checkRadios\">";
            echo "<div class=\"col-sm-6 col-lg-3 mb-4\">";
              echo "<p class=\"category\">Checkboxes</p>";
              echo "<div class=\"form-check\">";
                echo "<label class=\"form-check-label\">";
                  echo "<input class=\"form-check-input\" type=\"checkbox\">";
                  echo "<span class=\"form-check-sign\"></span>";
                  echo "Unchecked";
                echo "</label>";
              echo "</div>";
              echo "<div class=\"form-check\">";
                echo "<label class=\"form-check-label\">";
                  echo "<input class=\"form-check-input\" type=\"checkbox\" checked>";
                  echo "<span class=\"form-check-sign\"></span>";
                  echo "Checked";
                echo "</label>";
              echo "</div>";
              echo "<div class=\"form-check disabled\">";
                echo "<label class=\"form-check-label\">";
                  echo "<input class=\"form-check-input\" type=\"checkbox\" disabled>";
                  echo "<span class=\"form-check-sign\"></span>";
                  echo "Disabled Unchecked";
                echo "</label>";
              echo "</div>";
              echo "<div class=\"form-check disabled\">";
                echo "<label class=\"form-check-label\">";
                  echo "<input class=\"form-check-input\" type=\"checkbox\" checked disabled>";
                  echo "<span class=\"form-check-sign\"></span>";
                  echo "Disabled Checked";
                echo "</label>";
              echo "</div>";
            echo "</div>";
            echo "<div class=\"col-sm-6 col-lg-3 mb-4\">";
              echo "<p class=\"category\">Radios</p>";
              echo "<div class=\"form-check form-check-radio\">";
                echo "<label class=\"form-check-label\">";
                  echo "<input class=\"form-check-input\" type=\"radio\" name=\"exampleRadios\" id=\"exampleRadios1\" value=\"option1\">";
                  echo "<span class=\"form-check-sign\"></span>";
                  echo "Radio is off";
                echo "</label>";
              echo "</div>";
              echo "<div class=\"form-check form-check-radio\">";
                echo "<label class=\"form-check-label\">";
                  echo "<input class=\"form-check-input\" type=\"radio\" name=\"exampleRadios\" id=\"exampleRadios1\" value=\"option2\" checked>";
                  echo "<span class=\"form-check-sign\"></span>";
                  echo "Radio is on";
                echo "</label>";
              echo "</div>";
              echo "<div class=\"form-check form-check-radio disabled\">";
                echo "<label class=\"form-check-label\">";
                  echo "<input class=\"form-check-input\" type=\"radio\" name=\"exampleRadios1\" id=\"exampleRadios2\" value=\"option3\" disabled>";
                  echo "<span class=\"form-check-sign\"></span>";
                  echo "Disabled radio is off";
                echo "</label>";
              echo "</div>";
              echo "<div class=\"form-check form-check-radio disabled\">";
                echo "<label class=\"form-check-label\">";
                  echo "<input class=\"form-check-input\" type=\"radio\" name=\"exampleRadios1\" id=\"exampleRadios2\" value=\"option4\" disabled checked>";
                  echo "<span class=\"form-check-sign\"></span>";
                  echo "Disabled radio is on";
                echo "</label>";
              echo "</div>";
            echo "</div>";
            echo "<div class=\"col-sm-6 col-lg-3\">";
              echo "<p class=\"category\">Toggle Buttons</p>";
              echo "<input type=\"checkbox\" name=\"checkbox\" class=\"bootstrap-switch\" checked/>";
              echo "<br>";
              echo "<input type=\"checkbox\" name=\"checkbox\" class=\"bootstrap-switch\" data-on-label=\"ON\" data-off-label=\"OFF\" />";
            echo "</div>";
            echo "<div class=\"col-sm-6 col-lg-3\">";
              echo "<p class=\"category\">Sliders</p>";
              echo "<div id=\"sliderRegular\" class=\"slider\"></div>";
              echo "<br>";
              echo "<div id=\"sliderDouble\" class=\"slider slider-primary\"></div>";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section section-navbars\">";
        echo "<div class=\"container\" id=\"menu-dropdown\">";
          echo "<div class=\"row\">";
            echo "<div class=\"col-md-6\">";
              echo "<h4>Menu</h4>";
              echo "<nav class=\"navbar navbar-expand-lg bg-primary\">";
                echo "<div class=\"container\">";
                  echo "<a class=\"navbar-brand\" href=\"#\">Menu</a>";
                  echo "<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#example-navbar\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
                    echo "<span class=\"navbar-toggler-bar bar1\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar2\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar3\"></span>";
                  echo "</button>";
                  echo "<div class=\"collapse navbar-collapse\" id=\"example-navbar\" data-nav-image=\"assets/img/blurred-image-1.jpg\">";
                    echo "<ul class=\"navbar-nav\">";
                      echo "<li class=\"nav-item active\">";
                        echo "<a class=\"nav-link\" href=\"#\">";
                          echo "<p>Link</p>";
                        echo "</a>";
                      echo "</li>";
                      echo "<li class=\"nav-item\">";
                        echo "<a class=\"nav-link\" href=\"#\">";
                          echo "<p>Link</p>";
                        echo "</a>";
                      echo "</li>";
                      echo "<li class=\"nav-item dropdown\">";
                        echo "<a class=\"nav-link dropdown-toggle\" href=\"http://example.com\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">";
                          echo "<p>";
                            echo "Dropdown";
                          echo "</p>";
                        echo "</a>";
                        echo "<div class=\"dropdown-menu\" aria-labelledby=\"navbarDropdownMenuLink\">";
                          echo "<a class=\"dropdown-item\" href=\"#\">Action</a>";
                          echo "<a class=\"dropdown-item\" href=\"#\">Another action</a>";
                          echo "<a class=\"dropdown-item\" href=\"#\">Something else here</a>";
                        echo "</div>";
                      echo "</li>";
                    echo "</ul>";
                  echo "</div>";
                echo "</div>";
              echo "</nav>";
            echo "</div>";
            echo "<div class=\"col-md-6\">";
              echo "<h4>Menu with Icons</h4>";
              echo "<nav class=\"navbar navbar-expand-lg bg-info\">";
                echo "<div class=\"container\">";
                  echo "<a class=\"navbar-brand\" href=\"#\">Icons</a>";
                  echo "<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#example-navbar-icons\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
                    echo "<span class=\"navbar-toggler-bar bar1\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar2\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar3\"></span>";
                  echo "</button>";
                  echo "<div class=\"collapse navbar-collapse\" id=\"example-navbar-icons\">";
                    echo "<ul class=\"navbar-nav ml-auto\">";
                      echo "<li class=\"nav-item\">";
                        echo "<a class=\"nav-link\" href=\"#pablo\"><i class=\"now-ui-icons ui-1_send\" aria-hidden=\"true\"></i></a>";
                      echo "</li>";
                      echo "<li class=\"nav-item\">";
                        echo "<a class=\"nav-link\" href=\"#pablo\"><i class=\"now-ui-icons users_single-02\" aria-hidden=\"true\"></i></a>";
                      echo "</li>";
                      echo "<li class=\"nav-item dropdown\">";
                        echo "<a href=\"#\" class=\"nav-link dropdown-toggle\" id=\"navbarDropdownMenuLink\" data-toggle=\"dropdown\">";
                          echo "<i class=\"now-ui-icons ui-1_settings-gear-63\" aria-hidden=\"true\"></i>";
                        echo "</a>";
                        echo "<div class=\"dropdown-menu dropdown-menu-right\" aria-labelledby=\"navbarDropdownMenuLink\">";
                          echo "<a class=\"dropdown-header\">Dropdown header</a>";
                          echo "<a class=\"dropdown-item\" href=\"#\">Action</a>";
                          echo "<a class=\"dropdown-item\" href=\"#\">Another action</a>";
                          echo "<a class=\"dropdown-item\" href=\"#\">Something else here</a>";
                          echo "<div class=\"divider\"></div>";
                          echo "<a class=\"dropdown-item\" href=\"#\">Separated link</a>";
                          echo "<div class=\"divider\"></div>";
                          echo "<a class=\"dropdown-item\" href=\"#\">One more separated link</a>";
                        echo "</div>";
                      echo "</li>";
                    echo "</ul>";
                  echo "</div>";
                echo "</div>";
              echo "</nav>";
            echo "</div>";
          echo "</div>";
          echo "<h4>Navigation</h4>";
        echo "</div>";
        echo "<div id=\"navbar\">";
          echo "<div class=\"navigation-example\" style=\"background-image:url('assets/img/bg7.jpg')\">";
            echo "<!-- Navbar Primary  -->";
            echo "<nav class=\"navbar navbar-expand-lg bg-primary\">";
              echo "<div class=\"container\">";
                echo "<div class=\"navbar-translate\">";
                  echo "<a class=\"navbar-brand\" href=\"#pablo\">Primary color</a>";
                  echo "<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#example-navbar-primary\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
                    echo "<span class=\"navbar-toggler-bar bar1\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar2\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar3\"></span>";
                  echo "</button>";
                echo "</div>";
                echo "<div class=\"collapse navbar-collapse\" id=\"example-navbar-primary\">";
                  echo "<ul class=\"navbar-nav ml-auto\">";
                    echo "<li class=\"nav-item active\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"now-ui-icons objects_globe\"></i>";
                        echo "<p>Discover</p>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"now-ui-icons users_circle-08\"></i>";
                        echo "<p>Profile</p>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"now-ui-icons ui-1_settings-gear-63\"></i>";
                        echo "<p>Settings</p>";
                      echo "</a>";
                    echo "</li>";
                  echo "</ul>";
                echo "</div>";
              echo "</div>";
            echo "</nav>";
            echo "<!-- End Navbar Primary -->";
            echo "<!-- Navbar Info -->";
            echo "<nav class=\"navbar navbar-expand-lg bg-info\">";
              echo "<div class=\"container\">";
                echo "<div class=\"navbar-translate\">";
                  echo "<a class=\"navbar-brand\" href=\"#pablo\">Info Color</a>";
                  echo "<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#example-navbar-info\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
                    echo "<span class=\"navbar-toggler-bar bar1\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar2\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar3\"></span>";
                  echo "</button>";
                echo "</div>";
                echo "<div class=\"collapse navbar-collapse\" id=\"example-navbar-info\">";
                  echo "<ul class=\"navbar-nav ml-auto\">";
                    echo "<li class=\"nav-item active\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<p>Discover</p>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<p>Profile</p>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<p>Settings</p>";
                      echo "</a>";
                    echo "</li>";
                  echo "</ul>";
                echo "</div>";
              echo "</div>";
            echo "</nav>";
            echo "<!-- End Navbar Info -->";
            echo "<!-- Navbar Success -->";
            echo "<nav class=\"navbar navbar-expand-lg bg-success\">";
              echo "<div class=\"container\">";
                echo "<div class=\"navbar-translate\">";
                  echo "<a class=\"navbar-brand\" href=\"#\">Success Color</a>";
                  echo "<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#example-navbar-success\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
                    echo "<span class=\"navbar-toggler-bar bar1\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar2\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar3\"></span>";
                  echo "</button>";
                echo "</div>";
                echo "<div class=\"collapse navbar-collapse\" id=\"example-navbar-success\">";
                  echo "<ul class=\"navbar-nav ml-auto\">";
                    echo "<li class=\"nav-item active\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"now-ui-icons objects_globe\"></i>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"now-ui-icons users_circle-08\"></i>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"now-ui-icons ui-1_settings-gear-63\"></i>";
                      echo "</a>";
                    echo "</li>";
                  echo "</ul>";
                echo "</div>";
              echo "</div>";
            echo "</nav>";
            echo "<!-- End Navbar Success -->";
            echo "<!-- Navbar Warning -->";
            echo "<nav class=\"navbar navbar-expand-lg bg-warning\">";
              echo "<div class=\"container\">";
                echo "<div class=\"navbar-translate\">";
                  echo "<a class=\"navbar-brand\" href=\"#pablo\">Warning Color</a>";
                  echo "<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#example-navbar-warning\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
                    echo "<span class=\"navbar-toggler-bar bar1\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar2\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar3\"></span>";
                  echo "</button>";
                echo "</div>";
                echo "<div class=\"collapse navbar-collapse\" id=\"example-navbar-warning\">";
                  echo "<ul class=\"navbar-nav ml-auto\">";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-facebook-square\"></i>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-twitter\"></i>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-google-plus\"></i>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-instagram\"></i>";
                      echo "</a>";
                    echo "</li>";
                  echo "</ul>";
                echo "</div>";
              echo "</div>";
            echo "</nav>";
            echo "<!-- End Navbar Warning -->";
            echo "<!-- Navbar Danger -->";
            echo "<nav class=\"navbar navbar-expand-lg bg-danger\">";
              echo "<div class=\"container\">";
                echo "<div class=\"navbar-translate\">";
                  echo "<a class=\"navbar-brand\" href=\"#pablo\">Danger Color</a>";
                  echo "<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#example-navbar-danger\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
                    echo "<span class=\"navbar-toggler-bar bar1\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar2\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar3\"></span>";
                  echo "</button>";
                echo "</div>";
                echo "<div class=\"collapse navbar-collapse\" id=\"example-navbar-danger\">";
                  echo "<ul class=\"navbar-nav ml-auto\">";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-facebook-square\"></i>";
                        echo "<p>Share</p>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-twitter\"></i>";
                        echo "<p>Tweet</p>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-pinterest\"></i>";
                        echo "<p>Pin</p>";
                      echo "</a>";
                    echo "</li>";
                  echo "</ul>";
                echo "</div>";
              echo "</div>";
            echo "</nav>";
            echo "<!-- End Navbar Danger -->";
            echo "<!-- Navbar Transparent -->";
            echo "<nav class=\"navbar navbar-expand-lg navbar-transparent\">";
              echo "<div class=\"container\">";
                echo "<div class=\"navbar-translate\">";
                  echo "<a class=\"navbar-brand\" href=\"#pablo\">Transparent</a>";
                  echo "<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#example-navbar-transparent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">";
                    echo "<span class=\"navbar-toggler-bar bar1\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar2\"></span>";
                    echo "<span class=\"navbar-toggler-bar bar3\"></span>";
                  echo "</button>";
                echo "</div>";
                echo "<div class=\"collapse navbar-collapse\" id=\"example-navbar-transparent\">";
                  echo "<ul class=\"navbar-nav ml-auto\">";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-facebook-square\"></i>";
                        echo "<p>Facebook</p>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-twitter\"></i>";
                        echo "<p>Twitter</p>";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" href=\"#pablo\">";
                        echo "<i class=\"fab fa-instagram\"></i>";
                        echo "<p>Instagram</p>";
                      echo "</a>";
                    echo "</li>";
                  echo "</ul>";
                echo "</div>";
              echo "</div>";
            echo "</nav>";
            echo "<!-- End Navbar Transparent-->";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<!-- End .section-navbars  -->";
      echo "<div class=\"section section-tabs\">";
        echo "<div class=\"container\">";
          echo "<div class=\"row\">";
            echo "<div class=\"col-md-10 ml-auto col-xl-6 mr-auto\">";
              echo "<p class=\"category\">Tabs with Icons on Card</p>";
              echo "<!-- Nav tabs -->";
              echo "<div class=\"card\">";
                echo "<div class=\"card-header\">";
                  echo "<ul class=\"nav nav-tabs justify-content-center\" role=\"tablist\">";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link active\" data-toggle=\"tab\" href=\"#home\" role=\"tab\">";
                        echo "<i class=\"now-ui-icons objects_umbrella-13\"></i> Home";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" data-toggle=\"tab\" href=\"#profile\" role=\"tab\">";
                        echo "<i class=\"now-ui-icons shopping_cart-simple\"></i> Profile";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" data-toggle=\"tab\" href=\"#messages\" role=\"tab\">";
                        echo "<i class=\"now-ui-icons shopping_shop\"></i> Messages";
                      echo "</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" data-toggle=\"tab\" href=\"#settings\" role=\"tab\">";
                        echo "<i class=\"now-ui-icons ui-2_settings-90\"></i> Settings";
                      echo "</a>";
                    echo "</li>";
                  echo "</ul>";
                echo "</div>";
                echo "<div class=\"card-body\">";
                  echo "<!-- Tab panes -->";
                  echo "<div class=\"tab-content text-center\">";
                    echo "<div class=\"tab-pane active\" id=\"home\" role=\"tabpanel\">";
                      echo "<p>I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. So when you get something that has the name Kanye West on it, it’s supposed to be pushing the furthest possibilities. I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus.</p>";
                    echo "</div>";
                    echo "<div class=\"tab-pane\" id=\"profile\" role=\"tabpanel\">";
                      echo "<p> I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. </p>";
                    echo "</div>";
                    echo "<div class=\"tab-pane\" id=\"messages\" role=\"tabpanel\">";
                      echo "<p>I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. So when you get something that has the name Kanye West on it, it’s supposed to be pushing the furthest possibilities. I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus.</p>";
                    echo "</div>";
                    echo "<div class=\"tab-pane\" id=\"settings\" role=\"tabpanel\">";
                      echo "<p>";
                        echo "\"I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.\"";
                      echo "</p>";
                    echo "</div>";
                  echo "</div>";
                echo "</div>";
              echo "</div>";
            echo "</div>";
            echo "<div class=\"col-md-10 ml-auto col-xl-6 mr-auto\">";
              echo "<p class=\"category\">Tabs with Background on Card</p>";
              echo "<!-- Tabs with Background on Card -->";
              echo "<div class=\"card\">";
                echo "<div class=\"card-header\">";
                  echo "<ul class=\"nav nav-tabs nav-tabs-neutral justify-content-center\" role=\"tablist\" data-background-color=\"orange\">";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link active\" data-toggle=\"tab\" href=\"#home1\" role=\"tab\">Home</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" data-toggle=\"tab\" href=\"#profile1\" role=\"tab\">Profile</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" data-toggle=\"tab\" href=\"#messages1\" role=\"tab\">Messages</a>";
                    echo "</li>";
                    echo "<li class=\"nav-item\">";
                      echo "<a class=\"nav-link\" data-toggle=\"tab\" href=\"#settings1\" role=\"tab\">Settings</a>";
                    echo "</li>";
                  echo "</ul>";
                echo "</div>";
                echo "<div class=\"card-body\">";
                  echo "<!-- Tab panes -->";
                  echo "<div class=\"tab-content text-center\">";
                    echo "<div class=\"tab-pane active\" id=\"home1\" role=\"tabpanel\">";
                      echo "<p>I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. So when you get something that has the name Kanye West on it, it’s supposed to be pushing the furthest possibilities. I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus.</p>";
                    echo "</div>";
                    echo "<div class=\"tab-pane\" id=\"profile1\" role=\"tabpanel\">";
                      echo "<p> I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. </p>";
                    echo "</div>";
                    echo "<div class=\"tab-pane\" id=\"messages1\" role=\"tabpanel\">";
                      echo "<p>I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at. So when you get something that has the name Kanye West on it, it’s supposed to be pushing the furthest possibilities. I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus.</p>";
                    echo "</div>";
                    echo "<div class=\"tab-pane\" id=\"settings1\" role=\"tabpanel\">";
                      echo "<p>";
                        echo "\"I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.\"";
                      echo "</p>";
                    echo "</div>";
                  echo "</div>";
                echo "</div>";
              echo "</div>";
              echo "<!-- End Tabs on plain Card -->";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<!-- End Section Tabs -->";
      echo "<div class=\"section section-pagination\">";
        echo "<div class=\"container\">";
          echo "<div class=\"row\">";
            echo "<div class=\"col-md-6\">";
              echo "<h4>Progress Bars</h4>";
              echo "<div class=\"progress-container\">";
                echo "<span class=\"progress-badge\">Default</span>";
                echo "<div class=\"progress\">";
                  echo "<div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 25%;\">";
                    echo "<span class=\"progress-value\">25%</span>";
                  echo "</div>";
                echo "</div>";
              echo "</div>";
              echo "<div class=\"progress-container progress-primary\">";
                echo "<span class=\"progress-badge\">Primary</span>";
                echo "<div class=\"progress\">";
                  echo "<div class=\"progress-bar progress-bar-warning\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%;\">";
                    echo "<span class=\"progress-value\">60%</span>";
                  echo "</div>";
                echo "</div>";
              echo "</div>";
              echo "<br>";
              echo "<h4>Navigation Pills</h4>";
              echo "<ul class=\"nav nav-pills nav-pills-primary nav-pills-just-icons\" role=\"tablist\">";
                echo "<li class=\"nav-item\">";
                  echo "<a class=\"nav-link\" data-toggle=\"tab\" href=\"#active\" role=\"tablist\">";
                    echo "<i class=\"far fa-gem\"></i>";
                  echo "</a>";
                echo "</li>";
                echo "<li class=\"nav-item\">";
                  echo "<a class=\"nav-link active\" data-toggle=\"tab\" href=\"#link\" role=\"tablist\">";
                    echo "<i class=\"fa fa-thermometer-full\"></i>";
                  echo "</a>";
                echo "</li>";
                echo "<li class=\"nav-item\">";
                  echo "<a class=\"nav-link\" data-toggle=\"tab\" href=\"#link\" role=\"tablist\">";
                    echo "<i class=\"fa fa-suitcase\"></i>";
                  echo "</a>";
                echo "</li>";
                echo "<li class=\"nav-item\">";
                  echo "<a class=\"nav-link disabled\" data-toggle=\"tab\" href=\"#disabled\" role=\"tablist\">";
                    echo "<i class=\"fa fa-exclamation\"></i>";
                  echo "</a>";
                echo "</li>";
              echo "</ul>";
            echo "</div>";
            echo "<div class=\"col-sm-6\">";
              echo "<h4>Pagination</h4>";
              echo "<ul class=\"pagination pagination-primary\">";
                echo "<li class=\"page-item active\">";
                  echo "<a class=\"page-link\" href=\"#\">1</a>";
                echo "</li>";
                echo "<li class=\"page-item\">";
                  echo "<a class=\"page-link\" href=\"#link\">2</a>";
                echo "</li>";
                echo "<li class=\"page-item\">";
                  echo "<a class=\"page-link\" href=\"#link\">3</a>";
                echo "</li>";
                echo "<li class=\"page-item\">";
                  echo "<a class=\"page-link\" href=\"#link\">4</a>";
                echo "</li>";
                echo "<li class=\"page-item\">";
                  echo "<a class=\"page-link\" href=\"#link\">5</a>";
                echo "</li>";
              echo "</ul>";
              echo "<ul class=\"pagination\">";
                echo "<li class=\"page-item\">";
                  echo "<a class=\"page-link\" href=\"#link\" aria-label=\"Previous\">";
                    echo "<span aria-hidden=\"true\"><i class=\"fa fa-angle-double-left\" aria-hidden=\"true\"></i></span>";
                  echo "</a>";
                echo "</li>";
                echo "<li class=\"page-item\">";
                  echo "<a class=\"page-link\" href=\"#link\">1</a>";
                echo "</li>";
                echo "<li class=\"page-item active\">";
                  echo "<a class=\"page-link\" href=\"#link\">2</a>";
                echo "</li>";
                echo "<li class=\"page-item\">";
                  echo "<a class=\"page-link\" href=\"#link\">3</a>";
                echo "</li>";
                echo "<li class=\"page-item\">";
                  echo "<a class=\"page-link\" href=\"#link\" aria-label=\"Next\">";
                    echo "<span aria-hidden=\"true\"><i class=\"fa fa-angle-double-right\" aria-hidden=\"true\"></i></span>";
                  echo "</a>";
                echo "</li>";
              echo "</ul>";
              echo "<br>";
              echo "<h4>Labels</h4>";
              echo "<span class=\"badge badge-default\">Default</span>";
              echo "<span class=\"badge badge-primary\">Primary</span>";
              echo "<span class=\"badge badge-success\">Success</span>";
              echo "<span class=\"badge badge-info\">Info</span>";
              echo "<span class=\"badge badge-warning\">Warning</span>";
              echo "<span class=\"badge badge-danger\">Danger</span>";
              echo "<span class=\"badge badge-neutral\">Neutral</span";
            echo "</div>";
          echo "</div>";
          echo "<br>";
          echo "<div class=\"space\"></div>";
          echo "<h4>Notifications</h4>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section section-notifications\">";
        echo "<div class=\"alert alert-success\" role=\"alert\">";
          echo "<div class=\"container\">";
            echo "<div class=\"alert-icon\">";
              echo "<i class=\"now-ui-icons ui-2_like\"></i>";
            echo "</div>";
            echo "<strong>Well done!</strong> You successfully read this important alert message.";
            echo "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">";
              echo "<span aria-hidden=\"true\">";
                echo "<i class=\"now-ui-icons ui-1_simple-remove\"></i>";
              echo "</span>";
            echo "</button>";
          echo "</div>";
        echo "</div>";
        echo "<div class=\"alert alert-info\" role=\"alert\">";
          echo "<div class=\"container\">";
            echo "<div class=\"alert-icon\">";
              echo "<i class=\"now-ui-icons travel_info\"></i>";
            echo "</div>";
            echo "<strong>Heads up!</strong> This alert needs your attention, but it's not super important.";
            echo "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">";
              echo "<span aria-hidden=\"true\">";
                echo "<i class=\"now-ui-icons ui-1_simple-remove\"></i>";
              echo "</span>";
            echo "</button>";
          echo "</div>";
        echo "</div>";
        echo "<div class=\"alert alert-warning\" role=\"alert\">";
          echo "<div class=\"container\">";
            echo "<div class=\"alert-icon\">";
              echo "<i class=\"now-ui-icons ui-1_bell-53\"></i>";
            echo "</div>";
            echo "<strong>Warning!</strong> Better check yourself, you're not looking too good.";
            echo "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">";
              echo "<span aria-hidden=\"true\">";
                echo "<i class=\"now-ui-icons ui-1_simple-remove\"></i>";
              echo "</span>";
            echo "</button>";
          echo "</div>";
        echo "</div>";
        echo "<div class=\"alert alert-danger\" role=\"alert\">";
          echo "<div class=\"container\">";
            echo "<div class=\"alert-icon\">";
              echo "<i class=\"now-ui-icons objects_support-17\"></i>";
            echo "</div>";
            echo "<strong>Oh snap!</strong> Change a few things up and try submitting again.";
            echo "<button type=\"button\" class=\"close\" data-dismiss=\"alert\" aria-label=\"Close\">";
              echo "<span aria-hidden=\"true\">";
                echo "<i class=\"now-ui-icons ui-1_simple-remove\"></i>";
              echo "</span>";
            echo "</button>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<!--  end notifications -->";
      echo "<!-- Typography -->";
      echo "<div class=\"section\">";
        echo "<div class=\"container\">";
          echo "<h3 class=\"title\">Typography</h3>";
          echo "<div id=\"typography\">";
            echo "<div class=\"row\">";
              echo "<div class=\"col-md-12\">";
                echo "<div class=\"typography-line\">";
                  echo "<h1>";
                    echo "<span>Header 1</span>The Life of Now UI Kit </h1>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<h2>";
                    echo "<span>Header 2</span>The Life of Now UI Kit</h2>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<h3>";
                    echo "<span>Header 3</span>The Life of Now UI Kit</h3>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<h4>";
                    echo "<span>Header 4</span>The Life of Now UI Kit</h4>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<h5>";
                    echo "<span>Header 5</span>The Life of Now UI Kit</h5>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<h6>";
                    echo "<span>Header 6</span>The Life of Now UI Kit</h6>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<p>";
                    echo "<span>Paragraph</span>";
                    echo "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.";
                  echo "</p>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<span>Quote</span>";
                  echo "<blockquote>";
                    echo "<p class=\"blockquote blockquote-primary\">";
                      echo "\"I will be the leader of a company that ends up being worth billions of dollars, because I got the answers. I understand culture. I am the nucleus. I think that’s a responsibility that I have, to push possibilities, to show people, this is the level that things could be at.\"";
                      echo "<br>";
                      echo "<br>";
                      echo "<small>";
                        echo "- Noaa";
                      echo "</small>";
                    echo "</p>";
                  echo "</blockquote>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<span>Muted Text</span>";
                  echo "<p class=\"text-muted\">";
                    echo "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...";
                  echo "</p>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<span>Primary Text</span>";
                  echo "<p class=\"text-primary\">";
                    echo "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...</p>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<span>Info Text</span>";
                  echo "<p class=\"text-info\">";
                    echo "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<span>Success Text</span>";
                  echo "<p class=\"text-success\">";
                    echo "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<span>Warning Text</span>";
                  echo "<p class=\"text-warning\">";
                    echo "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers...";
                  echo "</p>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<span>Danger Text</span>";
                  echo "<p class=\"text-danger\">";
                    echo "I will be the leader of a company that ends up being worth billions of dollars, because I got the answers... </p>";
                echo "</div>";
                echo "<div class=\"typography-line\">";
                  echo "<h2>";
                    echo "<span>Small Tag</span>";
                    echo "Header with small subtitle";
                    echo "<br>";
                    echo "<small>Use \"small\" tag for the headers</small>";
                  echo "</h2>";
                echo "</div>";
              echo "</div>";
            echo "</div>";
          echo "</div>";
          echo "<div class=\"space-50\"></div>";
          echo "<div id=\"images\">";
            echo "<h4>Images</h4>";
            echo "<div class=\"row\">";
              echo "<div class=\"col-sm-2\">";
                echo "<p class=\"category\">Image</p>";
                echo "<img src=\"./assets/img/julie.jpg\" alt=\"Rounded Image\" class=\"rounded\">";
              echo "</div>";
              echo "<div class=\"col-sm-2\">";
                echo "<p class=\"category\">Circle Image</p>";
                echo "<img src=\"./assets/img/julie.jpg\" alt=\"Circle Image\" class=\"rounded-circle\">";
              echo "</div>";
              echo "<div class=\"col-sm-2\">";
                echo "<p class=\"category\">Raised</p>";
                echo "<img src=\"./assets/img/julie.jpg\" alt=\"Raised Image\" class=\"rounded img-raised\">";
              echo "</div>";
              echo "<div class=\"col-sm-2\">";
                echo "<p class=\"category\">Circle Raised</p>";
                echo "<img src=\"./assets/img/julie.jpg\" alt=\"Thumbnail Image\" class=\"rounded-circle img-raised\">";
              echo "</div>";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section section-javascript\" id=\"javascriptComponents\">";
        echo "<div class=\"container\">";
          echo "<h3 class=\"title\">Javascript components</h3>";
          echo "<div class=\"row\" id=\"modals\">";
            echo "<div class=\"col-md-6\">";
              echo "<h4>Modal</h4>";
              echo "<button class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#myModal\">";
                echo "Launch Modal";
              echo "</button>";
              echo "<button class=\"btn btn-warning\" data-toggle=\"modal\" data-target=\"#myModal1\">";
                echo "Launch Modal Mini";
              echo "</button>";
            echo "</div>";
            echo "<div class=\"col-md-6\">";
              echo "<h4>Popovers</h4>";
              echo "<button type=\"button\" class=\"btn btn-default\" data-container=\"body\" data-original-title=\"Popover On Left\" data-toggle=\"popover\" data-placement=\"left\" data-content=\"Here will be some very useful information about his popover.\" data-color=\"primary\">";
                echo "On left";
              echo "</button>";
              echo "<button type=\"button\" class=\"btn btn-default\" data-container=\"body\" data-original-title=\"Popover on Top\" data-toggle=\"popover\" data-placement=\"top\" data-content=\"Here will be some very useful information about his popover.\">";
                echo "On top";
              echo "</button>";
              echo "<button type=\"button\" class=\"btn btn-default\" data-container=\"body\" data-original-title=\"Popover on Right\" data-toggle=\"popover\" data-placement=\"right\" data-content=\"Here will be some very useful information about his popover.<br> Here will be some very useful information about his popover.\">";
                echo "On right";
              echo "</button>";
              echo "<button type=\"button\" class=\"btn btn-default\" data-container=\"body\" data-original-title=\"Popover on Bottom\" data-toggle=\"popover\" data-placement=\"bottom\" data-content=\"Here will be some very useful information about his popover.\">";
                echo "On bottom";
              echo "</button>";
            echo "</div>";
            echo "<br />";
            echo "<br />";
            echo "<div class=\"col-md-6\">";
              echo "<h4>Datepicker</h4>";
              echo "<div class=\"row\">";
                echo "<div class=\"col-md-6\">";
                  echo "<div class=\"datepicker-container\">";
                    echo "<div class=\"form-group\">";
                      echo "<input type=\"text\" class=\"form-control date-picker\" value=\"10/05/2016\" data-datepicker-color=\"primary\">";
                    echo "</div>";
                  echo "</div>";
                echo "</div>";
              echo "</div>";
            echo "</div>";
            echo "<div class=\"col-md-6\">";
              echo "<h4>Tooltips</h4>";
              echo "<button type=\"button\" class=\"btn btn-default btn-tooltip\" data-toggle=\"tooltip\" data-placement=\"left\" title=\"Tooltip on left\" data-container=\"body\" data-animation=\"true\" data-delay=\"100\">On left</button>";
              echo "<button type=\"button\" class=\"btn btn-default btn-tooltip\" data-toggle=\"tooltip\" data-placement=\"top\" title=\"Tooltip on top\" data-container=\"body\" data-animation=\"true\">On top</button>";
              echo "<button type=\"button\" class=\"btn btn-default btn-tooltip\" data-toggle=\"tooltip\" data-placement=\"bottom\" title=\"Tooltip on bottom\" data-container=\"body\" data-animation=\"true\">On bottom</button>";
              echo "<button type=\"button\" class=\"btn btn-default btn-tooltip\" data-toggle=\"tooltip\" data-placement=\"right\" title=\"Tooltip on right\" data-container=\"body\" data-animation=\"true\">On right</button>";
              echo "<div class=\"clearfix\"></div>";
              echo "<br>";
              echo "<br>";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section\" id=\"carousel\">";
        echo "<div class=\"container\">";
          echo "<div class=\"title\">";
            echo "<h4>Carousel</h4>";
          echo "</div>";
          echo "<div class=\"row justify-content-center\">";
            echo "<div class=\"col-lg-8 col-md-12\">";
              echo "<div id=\"carouselExampleIndicators\" class=\"carousel slide\" data-ride=\"carousel\">";
                echo "<ol class=\"carousel-indicators\">";
                  echo "<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"0\" class=\"active\"></li>";
                  echo "<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"1\"></li>";
                  echo "<li data-target=\"#carouselExampleIndicators\" data-slide-to=\"2\"></li>";
                echo "</ol>";
                echo "<div class=\"carousel-inner\" role=\"listbox\">";
                  echo "<div class=\"carousel-item active\">";
                    echo "<img class=\"d-block\" src=\"assets/img/bg1.jpg\" alt=\"First slide\">";
                    echo "<div class=\"carousel-caption d-none d-md-block\">";
                      echo "<h5>Nature, United States</h5>";
                    echo "</div>";
                  echo "</div>";
                  echo "<div class=\"carousel-item\">";
                    echo "<img class=\"d-block\" src=\"assets/img/bg3.jpg\" alt=\"Second slide\">";
                    echo "<div class=\"carousel-caption d-none d-md-block\">";
                      echo "<h5>Somewhere Beyond, United States</h5>";
                    echo "</div>";
                  echo "</div>";
                  echo "<div class=\"carousel-item\">";
                    echo "<img class=\"d-block\" src=\"assets/img/bg4.jpg\" alt=\"Third slide\">";
                    echo "<div class=\"carousel-caption d-none d-md-block\">";
                      echo "<h5>Yellowstone National Park, United States</h5>";
                    echo "</div>";
                  echo "</div>";
                echo "</div>";
                echo "<a class=\"carousel-control-prev\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"prev\">";
                  echo "<i class=\"now-ui-icons arrows-1_minimal-left\"></i>";
                echo "</a>";
                echo "<a class=\"carousel-control-next\" href=\"#carouselExampleIndicators\" role=\"button\" data-slide=\"next\">";
                  echo "<i class=\"now-ui-icons arrows-1_minimal-right\"></i>";
                echo "</a>";
              echo "</div>";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section section-nucleo-icons\">";
        echo "<div class=\"container\">";
          echo "<div class=\"row\">";
            echo "<div class=\"col-lg-6 col-md-12\">";
              echo "<h2 class=\"title\">Nucleo Icons</h2>";
              echo "<h5 class=\"description\">";
                echo "Now UI Kit PRO comes with 100 custom icons made by our friends from NucleoApp. The official package contains over 2.100 thin icons which are looking great in combination with Now UI Kit PRO Make sure you check all of them and use those that you like the most.";
              echo "</h5>";
              echo "<!-- <div class=\"nucleo-container\">";
							echo "<img src=\"assets/img/nucleo.svg\" alt=\"\">";
						echo "</div> -->";
              echo "<a href=\"nucleo-icons.html\" class=\"btn btn-primary btn-round btn-lg\" target=\"_blank\">View Demo Icons</a>";
              echo "<a href=\"https://nucleoapp.com/?ref=1712\" class=\"btn btn-outline-primary btn-round btn-lg\" target=\"_blank\">View All Icons</a>";
            echo "</div>";
            echo "<div class=\"col-lg-6 col-md-12\">";
              echo "<div class=\"icons-container\">";
                echo "<i class=\"now-ui-icons ui-1_send\"></i>";
                echo "<i class=\"now-ui-icons ui-2_like\"></i>";
                echo "<i class=\"now-ui-icons transportation_air-baloon\"></i>";
                echo "<i class=\"now-ui-icons text_bold\"></i>";
                echo "<i class=\"now-ui-icons tech_headphones\"></i>";
                echo "<i class=\"now-ui-icons emoticons_satisfied\"></i>";
                echo "<i class=\"now-ui-icons shopping_cart-simple\"></i>";
                echo "<i class=\"now-ui-icons objects_spaceship\"></i>";
                echo "<i class=\"now-ui-icons media-2_note-03\"></i>";
                echo "<i class=\"now-ui-icons ui-2_favourite-28\"></i>";
                echo "<i class=\"now-ui-icons design_palette\"></i>";
                echo "<i class=\"now-ui-icons clothes_tie-bow\"></i>";
                echo "<i class=\"now-ui-icons location_pin\"></i>";
                echo "<i class=\"now-ui-icons objects_key-25\"></i>";
                echo "<i class=\"now-ui-icons travel_istanbul\"></i>";
              echo "</div>";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section\">";
        echo "<div class=\"container text-center\">";
          echo "<div class=\"row justify-content-md-center\">";
            echo "<div class=\"col-md-12 col-lg-8\">";
              echo "<h2 class=\"title\">Completed with examples</h2>";
              echo "<h5 class=\"description\">The kit comes with three pre-built pages to help you get started faster. You can change the text and images and you're good to go. More importantly, looking at them will give you a picture of what you can built with this powerful Bootstrap 4 ui kit.</h5>";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section section-signup\" style=\"background-image: url('assets/img/bg11.jpg'); background-size: cover; background-position: top center; min-height: 700px;\">";
        echo "<div class=\"container\">";
          echo "<div class=\"row\">";
            echo "<div class=\"card card-signup\" data-background-color=\"orange\">";
              echo "<form class=\"form\" method=\"\" action=\"\">";
                echo "<div class=\"card-header text-center\">";
                  echo "<h3 class=\"card-title title-up\">Sign Up</h3>";
                  echo "<div class=\"social-line\">";
                    echo "<a href=\"#pablo\" class=\"btn btn-neutral btn-facebook btn-icon btn-round\">";
                      echo "<i class=\"fab fa-facebook-square\"></i>";
                    echo "</a>";
                    echo "<a href=\"#pablo\" class=\"btn btn-neutral btn-twitter btn-icon btn-lg btn-round\">";
                      echo "<i class=\"fab fa-twitter\"></i>";
                    echo "</a>";
                    echo "<a href=\"#pablo\" class=\"btn btn-neutral btn-google btn-icon btn-round\">";
                      echo "<i class=\"fab fa-google-plus\"></i>";
                    echo "</a>";
                  echo "</div>";
                echo "</div>";
                echo "<div class=\"card-body\">";
                  echo "<div class=\"input-group no-border\">";
                    echo "<div class=\"input-group-prepend\">";
                      echo "<span class=\"input-group-text\">";
                        echo "<i class=\"now-ui-icons users_circle-08\"></i>";
                      echo "</span>";
                    echo "</div>";
                    echo "<input type=\"text\" class=\"form-control\" placeholder=\"First Name...\">";
                  echo "</div>";
                  echo "<div class=\"input-group no-border\">";
                    echo "<div class=\"input-group-prepend\">";
                      echo "<span class=\"input-group-text\">";
                        echo "<i class=\"now-ui-icons text_caps-small\"></i>";
                      echo "</span>";
                    echo "</div>";
                    echo "<input type=\"text\" placeholder=\"Last Name...\" class=\"form-control\" />";
                  echo "</div>";
                  echo "<div class=\"input-group no-border\">";
                    echo "<div class=\"input-group-prepend\">";
                      echo "<span class=\"input-group-text\">";
                        echo "<i class=\"now-ui-icons ui-1_email-85\"></i>";
                      echo "</span>";
                    echo "</div>";
                    echo "<input type=\"text\" class=\"form-control\" placeholder=\"Email...\">";
                  echo "</div>";
                  echo "<!-- If you want to add a checkbox to this form, uncomment this code -->";
                  echo "<!-- <div class=\"checkbox\">";
								echo "<input id=\"checkboxSignup\" type=\"checkbox\">";
									echo "<label for=\"checkboxSignup\">";
									echo "Unchecked";
									echo "</label>";
								echo "</div> -->";
                echo "</div>";
                echo "<div class=\"card-footer text-center\">";
                  echo "<a href=\"#pablo\" class=\"btn btn-neutral btn-round btn-lg\">Get Started</a>";
                echo "</div>";
              echo "</form>";
            echo "</div>";
          echo "</div>";
          echo "<div class=\"col text-center\">";
            echo "<a href=\"examples/login-page.html\" class=\"btn btn-outline-default btn-round btn-white btn-lg\" target=\"_blank\">View Login Page</a>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section section-examples\" data-background-color=\"black\">";
        echo "<div class=\"space-50\"></div>";
        echo "<div class=\"container text-center\">";
          echo "<div class=\"row\">";
            echo "<div class=\"col\">";
              echo "<a href=\"examples/landing-page.html\" target=\"_blank\">";
                echo "<img src=\"assets/img/landing.jpg\" alt=\"Image\" class=\"img-raised\">";
              echo "</a>";
              echo "<a href=\"examples/landing-page.html\" class=\"btn btn-outline-default btn-primary btn-round\">View Landing Page</a>";
            echo "</div>";
            echo "<div class=\"col\">";
              echo "<a href=\"examples/profile-page.html\" target=\"_blank\">";
                echo "<img src=\"assets/img/profile.jpg\" alt=\"Image\" class=\"img-raised\">";
              echo "</a>";
              echo "<a href=\"examples/profile-page.html\" class=\"btn btn-outline-default btn-primary btn-round\">View Profile Page</a>";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
      echo "<div class=\"section section-download\" id=\"#download-section\" data-background-color=\"black\">";
        echo "<div class=\"container\">";
          echo "<div class=\"row justify-content-md-center\">";
            echo "<div class=\"text-center col-md-12 col-lg-8\">";
              echo "<h3 class=\"title\">Do you love this Bootstrap 4 UI Kit?</h3>";
              echo "<h5 class=\"description\">Cause if you do, it can be yours for FREE. Hit the button below to navigate to Creative Tim or Invision where you can find the kit in HTML or Sketch/PSD format. Start a new project or give an old Bootstrap project a new look!</h5>";
            echo "</div>";
            echo "<div class=\"text-center col-md-12 col-lg-8\">";
              echo "<a href=\"https://www.creative-tim.com/product/now-ui-kit\" class=\"btn btn-primary btn-lg btn-round\" role=\"button\">";
                echo "Download HTML";
              echo "</a>";
              echo "<a href=\"https://www.invisionapp.com/now\" target=\"_blank\" class=\"btn btn-lg btn-outline-primary btn-round\" role=\"button\">";
                echo "Download PSD/Sketch";
              echo "</a>";
            echo "</div>";
          echo "</div>";
          echo "<br>";
          echo "<br>";
          echo "<br>";
          echo "<div class=\"row text-center mt-5\">";
            echo "<div class=\"col-md-8 ml-auto mr-auto\">";
              echo "<h2>Want more?</h2>";
              echo "<h5 class=\"description\">We've just launched";
                echo "<a href=\"http://demos.creative-tim.com/now-ui-kit-pro/presentation.html\" target=\"_blank\">Now UI Kit PRO</a>. It has a huge number of components, sections and example pages. Start Your Development With A Badass Bootstrap 4 UI Kit.</h5>";
            echo "</div>";
            echo "<div class=\"col-md-12\">";
              echo "<a href=\"http://demos.creative-tim.com/now-ui-kit-pro/presentation.html\" class=\"btn btn-neutral btn-round btn-lg\" target=\"_blank\">";
                echo "<i class=\"now-ui-icons arrows-1_share-66\"></i> Upgrade to PRO";
              echo "</a>";
            echo "</div>";
          echo "</div>";
          echo "<br>";
          echo "<br>";
          echo "<div class=\"row justify-content-md-center sharing-area text-center\">";
            echo "<div class=\"text-center col-md-12 col-lg-8\">";
              echo "<h3>Thank you for supporting us!</h3>";
            echo "</div>";
            echo "<div class=\"text-center col-md-12 col-lg-8\">";
              echo "<a target=\"_blank\" href=\"https://www.twitter.com/creativetim\" class=\"btn btn-neutral btn-icon btn-twitter btn-round btn-lg\" rel=\"tooltip\" title=\"Follow us\">";
                echo "<i class=\"fab fa-twitter\"></i>";
              echo "</a>";
              echo "<a target=\"_blank\" href=\"https://www.facebook.com/creativetim\" class=\"btn btn-neutral btn-icon btn-facebook btn-round btn-lg\" rel=\"tooltip\" title=\"Like us\">";
                echo "<i class=\"fab fa-facebook-square\"></i>";
              echo "</a>";
              echo "<a target=\"_blank\" href=\"https://www.linkedin.com/company-beta/9430489/\" class=\"btn btn-neutral btn-icon btn-linkedin btn-lg btn-round\" rel=\"tooltip\" title=\"Follow us\">";
                echo "<i class=\"fab fa-linkedin\"></i>";
              echo "</a>";
              echo "<a target=\"_blank\" href=\"https://github.com/creativetimofficial/now-ui-kit\" class=\"btn btn-neutral btn-icon btn-github btn-round btn-lg\" rel=\"tooltip\" title=\"Star on Github\">";
                echo "<i class=\"fab fa-github\"></i>";
              echo "</a>";
            echo "</div>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
    echo "</div>";
    echo "<!-- Sart Modal -->";
    echo "<div class=\"modal fade\" id=\"myModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">";
      echo "<div class=\"modal-dialog\">";
        echo "<div class=\"modal-content\">";
          echo "<div class=\"modal-header justify-content-center\">";
            echo "<button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-hidden=\"true\">";
              echo "<i class=\"now-ui-icons ui-1_simple-remove\"></i>";
            echo "</button>";
            echo "<h4 class=\"title title-up\">Modal title</h4>";
          echo "</div>";
          echo "<div class=\"modal-body\">";
            echo "<p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.";
            echo "</p>";
          echo "</div>";
          echo "<div class=\"modal-footer\">";
            echo "<button type=\"button\" class=\"btn btn-default\">Nice Button</button>";
            echo "<button type=\"button\" class=\"btn btn-danger\" data-dismiss=\"modal\">Close</button>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
    echo "</div>";
    echo "<!--  End Modal -->";
    echo "<!-- Mini Modal -->";
    echo "<div class=\"modal fade modal-mini modal-primary\" id=\"myModal1\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\" aria-hidden=\"true\">";
      echo "<div class=\"modal-dialog\">";
        echo "<div class=\"modal-content\">";
          echo "<div class=\"modal-header justify-content-center\">";
            echo "<div class=\"modal-profile\">";
              echo "<i class=\"now-ui-icons users_circle-08\"></i>";
            echo "</div>";
          echo "</div>";
          echo "<div class=\"modal-body\">";
            echo "<p>Always have an access to your profile</p>";
          echo "</div>";
          echo "<div class=\"modal-footer\">";
            echo "<button type=\"button\" class=\"btn btn-link btn-neutral\">Back</button>";
            echo "<button type=\"button\" class=\"btn btn-link btn-neutral\" data-dismiss=\"modal\">Close</button>";
          echo "</div>";
        echo "</div>";
      echo "</div>";
    echo "</div>";
    echo "<!--  End Modal -->";
    echo "<footer class=\"footer\" data-background-color=\"black\">";
      echo "<div class=\" container \">";
        echo "<nav>";
          echo "<ul>";
            echo "<li>";
              echo "<a href=\"https://www.creative-tim.com\">";
                echo "Creative Tim";
              echo "</a>";
            echo "</li>";
            echo "<li>";
              echo "<a href=\"http://presentation.creative-tim.com\">";
                echo "About Us";
              echo "</a>";
            echo "</li>";
            echo "<li>";
              echo "<a href=\"http://blog.creative-tim.com\">";
                echo "Blog";
              echo "</a>";
            echo "</li>";
          echo "</ul>";
        echo "</nav>";
        echo "<div class=\"copyright\" id=\"copyright\">";
          echo "&copy;";
          echo "<script>";
            echo "document.getElementById('copyright').appendChild(document.createTextNode(new Date().getFullYear()))";
          echo "</script>, Designed by";
          echo "<a href=\"https://www.invisionapp.com\" target=\"_blank\">Invision</a>. Coded by";
          echo "<a href=\"https://www.creative-tim.com\" target=\"_blank\">Creative Tim</a>.";
        echo "</div>";
      echo "</div>";
    echo "</footer>";
  echo "</div>";
  echo "<!--   Core JS Files   -->";
  echo "<script src=\"./assets/js/core/jquery.min.js\" type=\"text/javascript\"></script>";
  echo "<script src=\"./assets/js/core/popper.min.js\" type=\"text/javascript\"></script>";
  echo "<script src=\"./assets/js/core/bootstrap.min.js\" type=\"text/javascript\"></script>";
  echo "<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->";
  echo "<script src=\"./assets/js/plugins/bootstrap-switch.js\"></script>";
  echo "<!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->";
  echo "<script src=\"./assets/js/plugins/nouislider.min.js\" type=\"text/javascript\"></script>";
  echo "<!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->";
  echo "<script src=\"./assets/js/plugins/bootstrap-datepicker.js\" type=\"text/javascript\"></script>";
  echo "<!--  Google Maps Plugin    -->";
  echo "<script src=\"https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE\"></script>";
  echo "<!-- Control Center for Now Ui Kit: parallax effects, scripts for the example pages etc -->";
  echo "<script src=\"./assets/js/now-ui-kit.js?v=1.3.0\" type=\"text/javascript\"></script>";
  echo "<script>";
    echo "$(document).ready(function() {";
      echo "// the body of this function is in assets/js/now-ui-kit.js";
      echo "nowuiKit.initSliders();";
    echo "});";

    echo "function scrollToDownload() {";

      echo "if ($('.section-download').length != 0) {";
        echo "$(\"html, body\").animate({";
          echo "scrollTop: $('.section-download').offset().top";
        echo "}, 1000);";
      echo "}";
    echo "}";
  echo "</script>";
echo "</body>";

echo "</html>";